### PR TITLE
Test only: build with new Wercker docker image

### PR DESCRIPTION
**Pull request by stefanv**

### CODE REVIEW

**Comment by jni** [comment]
Looks like a winner! Shall I just merge this or do you want me to rebase mine?

**Comment by stefanv** [comment]
Sure, that works!

**Comment by jni** [comment]
Which one works?

**Comment by stefanv** [comment]
Either; rebase and merge or merge this one.

BTW, this does not build on HTMLBook; we should probably build that as a check too.

**Comment by jni** [comment]
I'll leave the HTMLBook build for a later PR. =)

**Comment by jni** [comment]
Incidentally, merging this changed the status on #234 to merged! Magic!

**Pull request merged**
