### PR TITLE
`bs4` is `beautifulsoup4`

### PR DESCRIPTION
**Pull request by jakirkham**
Replace `bs4` with `beautifulsoup4` as they are the same and the former is merely an alias.

---
This change is [Reviewable](https://reviewable.io/reviews/elegant-scipy/elegant-scipy/331)

### CODE REVIEW

**Comment by jni** [comment]
Thanks @jakirkham! Having you contribute here makes me very happy. =)

**Comment by jni** [comment]
Hmmm though actually the wercker build crashed, and appears to be related... Do we need to pin a version somewhere?

**Comment by jni** [comment]
Hmmm this is strange. @stefanv might have some insights...

**Comment by jakirkham** [comment]
Was thinking BeautifulSoup4 4.6.0 was causing the issue, but pinning doesn't seem to help. 😕

ref: https://app.wercker.com/elegant-scipy/elegant-scipy/runs/build/5b1626341af74e00013eb7b7?step=5b16265aa916600001137d74

**Comment by stefanv** [comment]
I have not been able to debug this issue; lxml is installed, and that
same environment works for me locally!

**Comment by jni** [comment]
Hmm, this is concerning, to say the least! I guess I vote for merging this anyway in that case...!

**Pull request closed without merging**
