### PR TITLE
Use latest skimage to build book

### PR DESCRIPTION
**Pull request by stefanv**
This change is [Reviewable](https://reviewable.io/reviews/elegant-scipy/elegant-scipy/201)

### CODE REVIEW

**Comment by stefanv** [comment]
Let's see if this helps.

**Comment by jni** [comment]
Wercker seems to be off for the holidays... =P

**Comment by stefanv** [comment]
https://app.wercker.com/elegant-scipy/elegant-scipy/runs/build/585b7759fa0268010047372c?step=585b779aeb723f0001731804

**Comment by jni** [comment]
isn't it git+https://github.com? Also I thought wercker was supposed to comment on this thing?

**Comment by stefanv** [comment]
Yeah, it's having issues with out gitter report hook for some reason.  Anyway, it's doing its work in the background.  Not sure why it is not reporting failures here.

**Comment by stefanv** [comment]
I got this far: https://app.wercker.com/elegant-scipy/elegant-scipy/runs/build/585b8fb552c0890100e77bcb?step=585b8fe3eb723f000173dfdb

??

**Comment by jni** [comment]
Hmm, is that after multiple retries? Weird error...!

**Comment by stefanv** [comment]
Maybe the memory allocation bug found by the Debian devs in `label`?

**Comment by jni** [comment]
@stefanv some context for the label error? I don't remember it...

**Pull request closed without merging**
