### PR TITLE
Ch5 fixes from Nelle

### PR DESCRIPTION
**Pull request by jni**

### CODE REVIEW

**Comment by stefanv** [comment]
Please rebase on master after merging HTMLBook branch.

**Comment by jni** [comment]
@stefanv rebased and build complete! =)

**Comment by stefanv** [comment]
I would recommend reverting the `todense` change.  `todense` is not only more readable, but also doesn't hide the dangerous cost you mention.

**Comment by jni** [comment]
Well, it should be `toarray` at any rate, which is a tad less readable. I get your point, but in many cases `.A` feels more readable to me because it gets out of the way of the actual computation... I think we should do it case-by-case. I'll make a note of it in the text, and revert some of the uses.

**Comment by stefanv** [comment]
OK, thanks, that works for me.

**Comment by NelleV** [comment]
Annoying reviewer n°3 is happy with those changes :D

**Comment by hdashnow** [comment]
Ready to merge @jni?

**Comment by jni** [comment]
Probably we should wait until I've got a chance to update all the .A/.toarray uses. Will try to get to it today.

**Comment by stefanv** [comment]
Ping @jni

**Comment by jni** [comment]
@stefanv here we go! =)

**Pull request merged**
