### PR TITLE
Remove invalid statement about book authored in Jupyter

### PR DESCRIPTION
**Pull request by stefanv**
This change is [Reviewable](https://reviewable.io/reviews/elegant-scipy/elegant-scipy/294)

### CODE REVIEW

**Comment by jni** [comment]
I don't think it's inaccurate to say we used Jupyter for the book, we just used some extensions. How about "this entire book was written using Notedown, an extension of Jupyter.

**Comment by jni** [comment]
Certainly, I would want to acknowledge the critical role that Jupyter played in the process.

**Comment by stefanv** [comment]
How about the truth?  This book was written in Markdown, and converted to Jupyter notebooks for execution and publishing.  Or, shorter: This entire book is executed in Jupyter before publication.

**Comment by stefanv** [comment]
How is this version?

**Pull request merged**
