### PR TITLE
Update and sync dependencies in `requirements.txt` and `environment.yml`

### PR DESCRIPTION
**Pull request by rossbar**
This PR addresses issue #349 by:

 * updating the versions of dependencies in both `environment.yml` and `requirements.txt` so that they are consistent with each other.
 * Verifying that creating the environment works using either `conda` or the `venv` module.
 * Updating the README with a few additional instructions on how to create the environment with using `venv` (for non-conda users).

Currently the `conda`-ish way of setting up the environment isn't tested at all in the CI. I don't have any experience with wercker, but it seems like adding the following to `wercker.yml` under the `build` pipeline might do the trick:

```yaml
    - script:
        name: test conda build
        code: |
          conda env create --name elegant-scipy -f environment.yml
```
I didn't add it because I don't want to break the CI for the repo. Let me know if this is something that would be of interest.

### CODE REVIEW

**Comment by jni** [comment]
This looks great, thanks @rossbar! I must admit I'm not sure about Wercker but it's worth adding that and seeing if it doesn't break. If it does break, you can always revert that commit!

Thanks!

**Comment by rossbar** [comment]
Ok, I think this is ready for review.

I tried modifying the wercker CI but my approach did not work. I reverted and ended up having to modify the `pip-install` step in the wercker `build` to force pip to re-install everything. At least the CI is working again, though it is still not testing the constructing of the conda environment

**Comment by stefanv** [comment]
Do we still want the force option in there?  Otherwise looks good, thanks!

**Comment by jni** [comment]
@stefanv worst case, it means there is no caching used on Werker envs, so I think it's fine to merge as is. We can revert if it causes trouble. Thanks again @rossbar!

**Pull request merged**
