### PR TITLE
[WIP] Chapter 7

### PR DESCRIPTION
**Pull request by jni**
hashtag hellyeah! =P

Obviously this is early, but there's definitely a chapter here. Thanks @stefanv for the great code that got this started. Comments welcome!

### CODE REVIEW

**Comment by jni** [comment]
As a preview, here are the two cost function plots, which are awesome, especially in their elegant MPL glory:

screen shot 2016-11-16 at 7 36 47 pm

screen shot 2016-11-16 at 7 30 58 pm

**Comment by stefanv** [comment]
Neat!  Can you place a white background or box around the legend in the
first plot?

**Comment by jni** [comment]
@stefanv I think this looks pretty great currently. I suggest merging and iterating in future PRs!

**Comment by jni** [comment]
@stefanv note also that I've rebased on the current master.

**Comment by jni** [comment]
@stefanv any thoughts on merging this? I want to Move Fast and Break Things™. =P

**Comment by jni** [comment]
@hdashnow And if you want to download and run this branch and offer suggestions, it would be much appreciated! =) Note that you can also push to it!

**Comment by stefanv** [comment]
Well, I wanted to review the PR... but...

**Comment by stefanv** [comment]
We clearly have a lot more work to do, but as you say: rapid iteration FTW.

**Comment by jni** [comment]
@stefanv feel free to add comments to this diff or raise issues based on your review!

**Pull request merged**
